const Actions = {
  // chat
  CHAT_INIT: 'CHAT_INIT',
  CHAT_ADD: 'CHAT_ADD',
  CHAT_ADD_MSG: 'CHAT_ADD_MSG',
  CHAT_REMOVE: 'CHAT_REMOVE',
  CHAT_INCREASE_UNREAD_MSG: 'CHAT_INCREASE_UNREAD_MSG',
  CHAT_UPDATE_LAST_MSG: 'CHAT_UPDATE_LAST_MSG',

  // company
  COMPANY_ADD: 'COMPANY_ADD',

  // contact
  CONTACT_INIT: 'CONTACT_INIT',
  CONTACT_SET_GROUP_EXPAND: 'CONTACT_SET_GROUP_EXPAND',

  // dialogue
  DIALOGUE_SET_CURRENT_ID: 'DIALOGUE_SET_CURRENT_ID',
  DIALOGUE_INIT_MSGS: 'DIALOGUE_INIT_MSGS',
  DIALOGUE_ADD_MESSAGE: 'DIALOGUE_ADD_MESSAGE',

  // msg
  MSG_ADD: 'MSG_ADD',
  MSG_REMOVE: 'MSG_REMOVE',

  // users
  USERS_ADD: 'USERS_ADD'
}

export default Actions;