const Actions = {
  // chat
  CHAT_INIT: 'CHAT_INIT',
  CHAT_ADD: 'CHAT_ADD',
  CHAT_REMOVE: 'CHAT_REMOVE',
  CHAT_SET_LASTREADMSGID: 'CHAT_SET_LASTREADMSGID',

  // company
  COMPANY_ADD: 'COMPANY_ADD',

  // contact
  CONTACT_INIT: 'CONTACT_INIT',
  CONTACT_SET_GROUP_EXPAND: 'CONTACT_SET_GROUP_EXPAND',

  // dialogue
  DIALOGUE_SET_CURRENT_ID: 'DIALOGUE_SET_CURRENT_ID',
  DIALOGUE_INIT_MSGS: 'DIALOGUE_INIT_MSGS',
  DIALOGUE_ADD_MESSAGE: 'DIALOGUE_ADD_MESSAGE',

  // msg
  MSG_ADD: 'MSG_ADD',
  MSG_REMOVE: 'MSG_REMOVE',

  // users
  USERS_ADD: 'USERS_ADD',
  USERS_UPDATE_AVATAR_LIST: 'USERS_UPDATE_AVATAR_LIST',

  // config
  CONFIG_SET: 'CONFIG_SET',

  // global config
  GLOBAL_CONFIG_SET: 'GLOBAL_CONFIG_SET',

  // room
  ROOM_ADD: 'ROOM_ADD',
  ROOM_REMOVE: 'ROOM_REMOVE',
}

export default Actions;