const DialogueActionTypes = {
  ON_LEFT_BUTTON_CLICK: 'ON_LEFT_BUTTON_CLICK',
  ON_RIGHT_BUTTON_CLICK: 'ON_RIGHT_BUTTON_CLICK',

  SET_CURRENT_ID: 'SET_CURRENT_ID',
  INIT_MSGS: 'INIT_MSGS',
  ADD_MESSAGE: 'ADD_MESSAGE',
};

export default DialogueActionTypes;